### ISSUE TITLE
Binary data transmission

### ISSUE THREAD

**Issue by MRtecno98** [SamueleAtzori/Servito#1]
What if I want to transmit binary data instead of Strings? How can I do that without converting all my data very slowly into a String?

**Comment by HellishOblivion** [comment]
You can't receive other types of data instead String.
Each reader keeps reading on a connection, when it finds a in this is casted to character.
When a reader finds the end char, specified in Protocol, it creates a new packet.
Then a worker will process that packet.
In the next release you can change end char for a connection or even for all.
Moreover I will change packet content's type, from String to int[]

**Comment by MRtecno98** [comment]
I'll suggest a byte array, this way is possible encoding and decoding every data and sending it through the connection

**Comment by HellishOblivion** [comment]
Ok, i released patch 1.
Now you can send only byte arrays through connections.
There's a new class to support this feature, DataParser.
It provides a simple way to convert data to byte arrays and, conversely, byte arrays to data.
